[package]
name = "dmytro/anime-blitz"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ByteNet = "ffrostflame/bytenet@0.4.6"
Vide = "centau/vide@0.3.1"
Lyra = "paradoxum-games/lyra@0.6.0"
Charm = "littensy/charm@0.10.0"
CharmSync = "littensy/charm-sync@0.3.0"
Sift = "csqrl/sift@0.0.11"